# Generated by Django 5.2 on 2025-04-28 15:29

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_count', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10), api.models.EvenSeatsValidator])),
                ('seat_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('reserved_seat_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)])),
                ('canceled', models.BooleanField(default=False)),
                ('total_price', models.PositiveIntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.table')),
            ],
        ),
    ]
